In [2]:
!pip install Numpy 

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [2]:
list = [1,2,3,4]

In [3]:
type(list)

list

In [4]:
arr = np.array(list)

In [5]:
arr

array([1, 2, 3, 4])

In [6]:
type(arr)

numpy.ndarray

In [ ]:
1
2
3
4

In [7]:
arr.size

4

In [9]:
z = np.zeros(10)

In [10]:
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
z = np.ones(10)

In [12]:
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
#one dimensional array
o=np.array([1,2,3,4])

In [14]:
o.ndim

1

In [15]:
o.shape

(4,)

In [17]:
#2-d array to represent matrix, 1dim array as its elements
x = np.array([[1,2,3],[4,5,6],[7,8,9],[4,9,6]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [4, 9, 6]])

In [18]:
x.ndim

2

In [19]:
x.shape

(4, 3)

#3-d -> has 2d array as its elements

In [20]:
x = x.reshape(3,2,2)
x

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[9, 4],
        [9, 6]]])

In [21]:
x.ndim

3

In [22]:
x.shape


(3, 2, 2)

In [27]:
x=x.reshape(3,4)
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 4, 9, 6]])

In [28]:
x.shape

(3, 4)

In [30]:
x.ndim

2

# Indexing

## Accessing 1 d array

In [31]:
arr =np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [32]:
arr[2]

3

In [33]:
arr[1]+arr[2]

5

## Accessing 2 d array

In [34]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [35]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [37]:
print("2nd element in 1st dim", arr[0,1])

2nd element n 1st dim 2


In [38]:
print("2nd element in 2nd dim", arr[1,1])

2nd element in 2nd dim 7


In [39]:
print("5th element in 2nd dim", arr[1,4])

5th element in 2nd dim 10


In [40]:
#linspace linspace(strt,end,no. of values between 0 and 10)
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [45]:
#identity matrix eye(dimension)
x=np.eye(3)

In [44]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [46]:
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
x.shape

(3, 3)

In [52]:
#generate random numbers
np.random.randint(0,10,20)

array([5, 8, 2, 3, 3, 7, 4, 2, 0, 6, 7, 4, 8, 8, 3, 6, 0, 6, 2, 0])

In [53]:
#generate 2d matrix of random numbers
np.random.rand(3,3)

array([[0.6562111 , 0.87897401, 0.21065883],
       [0.2649187 , 0.77642261, 0.84056116],
       [0.55529247, 0.14782248, 0.54207359]])

In [54]:
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [55]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [56]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [57]:
#max value in this array
arr.max()

10

In [58]:
#what loc is max value present (index value)
arr.argmax()

9

In [59]:
arr.min()

1

In [65]:
a=np.arange(0,11,2) #start,end,spacing evenly spaced value in given interval

# Slicing


In [66]:
a

array([ 0,  2,  4,  6,  8, 10])

In [67]:
a[1:3]  #[start value : end value+1]

array([2, 4])

In [69]:
a = np.array([[1,2,3],[2,3,4],[4,5,6]])

In [70]:
a

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [71]:
a[0][0:2]

array([1, 2])

In [73]:
a[0:0+1,0:1+1] # a[row:end+1,col:col+1]

array([[1, 2]])

In [74]:
a[0:1,0:2]

array([[1, 2]])

In [75]:
a[0:1,0:3]

array([[1, 2, 3]])

In [76]:
a[2:3,0:2]

array([[4, 5]])

In [77]:
a[0:2,1:3]

array([[2, 3],
       [3, 4]])

## add two arrays

In [78]:
a

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [79]:
a = np.arange(0,11,2)

In [80]:
a

array([ 0,  2,  4,  6,  8, 10])

In [81]:
a1 = np.arange(0,11,2)

In [82]:
a1

array([ 0,  2,  4,  6,  8, 10])

In [83]:
c=a+a1

In [84]:
c

array([ 0,  4,  8, 12, 16, 20])

In [85]:
np.sqrt(c)

array([0.        , 2.        , 2.82842712, 3.46410162, 4.        ,
       4.47213595])

In [86]:
np.sin(c)

array([ 0.        , -0.7568025 ,  0.98935825, -0.53657292, -0.28790332,
        0.91294525])

In [87]:
#copy one array to another array
arr = np.array([1,2,3,4,5])
x=arr.copy()

In [88]:
x

array([1, 2, 3, 4, 5])

In [89]:
arr

array([1, 2, 3, 4, 5])

In [90]:
arr[0]=31

In [91]:
arr

array([31,  2,  3,  4,  5])

In [92]:
x

array([1, 2, 3, 4, 5])

In [93]:
z=arr.view()

In [94]:
z

array([31,  2,  3,  4,  5])

In [95]:
arr[1]=45

In [96]:
arr

array([31, 45,  3,  4,  5])

In [97]:
z

array([31, 45,  3,  4,  5])

In [102]:
#create an array 5*5 which should contain from o to 24

a = np.arange(0,25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])